# Created by Jekyll Writer
title: A Simpler Blog
email: NoAnyPurpose@gmail.com
description: 'Physics, Technology, Myself'
baseurl: /Jekyll_Writer
url: ''
permalink: '/:year/:title/'
markdown: kramdown
